/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Color;

/**
 *
 * @author ADMIN
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jpnAdd = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jpnAdd1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jpnAdd2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 0, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons8_user_64px.png"))); // NOI18N
        jLabel1.setText("ADMIN");
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 180, 70));

        jpnAdd.setBackground(new java.awt.Color(102, 0, 255));
        jpnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpnAddMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpnAddMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpnAddMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jpnAddMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jpnAddMouseReleased(evt);
            }
        });
        jpnAdd.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon("D:\\Download\\1affdfc8dcc606e9df4fd8de96fe43e9.png")); // NOI18N
        jpnAdd.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 50, 50));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Thêm Tài Khoản");
        jpnAdd.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 170, 40));

        jPanel2.add(jpnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 300, 70));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 300, 0));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("_______________________________________________________");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 280, 20));

        jpnAdd1.setBackground(new java.awt.Color(102, 0, 255));
        jpnAdd1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpnAdd1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpnAdd1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpnAdd1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jpnAdd1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jpnAdd1MouseReleased(evt);
            }
        });
        jpnAdd1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon("D:\\Download\\1affdfc8dcc606e9df4fd8de96fe43e9.png")); // NOI18N
        jpnAdd1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 50, 50));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Cập Nhật Tài Khoản");
        jpnAdd1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 170, 40));

        jPanel2.add(jpnAdd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 300, 70));

        jpnAdd2.setBackground(new java.awt.Color(102, 0, 255));
        jpnAdd2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpnAdd2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpnAdd2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpnAdd2MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jpnAdd2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jpnAdd2MouseReleased(evt);
            }
        });
        jpnAdd2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon("D:\\Download\\1affdfc8dcc606e9df4fd8de96fe43e9.png")); // NOI18N
        jpnAdd2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 50, 50));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Xóa Tài Khoản");
        jpnAdd2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 170, 40));

        jPanel2.add(jpnAdd2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 300, 70));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 530));

        jPanel3.setBackground(new java.awt.Color(87, 37, 170));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 680, 60));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("QUẢN LÝ NHÂN VIÊN");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 680, 80));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 530));

        setSize(new java.awt.Dimension(994, 536));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jpnAddMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnAddMouseReleased
        
    }//GEN-LAST:event_jpnAddMouseReleased

    private void jpnAddMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnAddMousePressed
//        jpnAdd.setBackground(Color.BLUE);
    }//GEN-LAST:event_jpnAddMousePressed

    private void jpnAddMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnAddMouseEntered
        // TODO add your handling code here:
                jpnAdd.setBackground(Color.BLUE);

    }//GEN-LAST:event_jpnAddMouseEntered

    private void jpnAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnAddMouseClicked
        // TODO add your handling code here:
                jpnAdd.setBackground(new Color(186, 31, 122));

    }//GEN-LAST:event_jpnAddMouseClicked

    private void jpnAddMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnAddMouseExited
        // TODO add your handling code here:
                jpnAdd.setBackground(new Color(102,0,255));

    }//GEN-LAST:event_jpnAddMouseExited

    private void jpnAdd1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnAdd1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jpnAdd1MouseClicked

    private void jpnAdd1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnAdd1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jpnAdd1MouseEntered

    private void jpnAdd1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnAdd1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jpnAdd1MouseExited

    private void jpnAdd1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnAdd1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpnAdd1MousePressed

    private void jpnAdd1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnAdd1MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jpnAdd1MouseReleased

    private void jpnAdd2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnAdd2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jpnAdd2MouseClicked

    private void jpnAdd2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnAdd2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jpnAdd2MouseEntered

    private void jpnAdd2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnAdd2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jpnAdd2MouseExited

    private void jpnAdd2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnAdd2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpnAdd2MousePressed

    private void jpnAdd2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnAdd2MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jpnAdd2MouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel jpnAdd;
    private javax.swing.JPanel jpnAdd1;
    private javax.swing.JPanel jpnAdd2;
    // End of variables declaration//GEN-END:variables
}
