package view;

import controller.AdminListener;
import controller.StaffManagerListener;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Image;
import java.util.Vector;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import model.Adopter;
import model.managementStaff;
import view.Thong_bao_nhan_vien.main_thong_bao_nv;
import view.thong_bao_cho_trang_chu.main_thong_bao;
import view.viewStaffManager.AdopterManager;
import view.viewStaffManager.ExtracurricularActivities;
import view.viewStaffManager.CharityActivityManager;
import view.viewStaffManager.ChildrenManager;
import view.viewStaffManager.EquipmentManager;
import view.viewStaffManager.IntroductorManager;
import view.viewStaffManager.StaffManager;

public class staff extends javax.swing.JFrame {

    StaffManager staffManager = new StaffManager();
    EquipmentManager equipmentManager = new EquipmentManager();
    ChildrenManager childManager = new ChildrenManager();
    ExtracurricularActivities extracManager = new ExtracurricularActivities();
    CharityActivityManager charityManager = new CharityActivityManager();
    IntroductorManager introManager = new IntroductorManager();
    main_thong_bao_nv StaffNotifi = new main_thong_bao_nv();
    main_thong_bao News = new main_thong_bao();
    AdopterManager adop = new AdopterManager();
    Login log = new Login();
    AdminListener admin = new AdminListener();

    //get id to jlabel StaffName
    String ID_NVQL;

    public String getID_NVQL() {
        return ID_NVQL;
    }

    public void setID_NVQL(String ID_NVQL) {
        this.ID_NVQL = ID_NVQL;
    }

    /**
     * Creates new form staff
     */
    public staff() {
        staffManager.setVisible(true);
        initComponents();
        this.setExtendedState(this.MAXIMIZED_BOTH);
        setMenuColor(jlb1);
        jbtExtracurricular.setVisible(false);
        jbtCharity.setVisible(false);
        jbtSendStaff.setVisible(false);
        jbtSendmain.setVisible(false);
        setCursor();
    }

    public void setCursor() {
        jbtStaffManager.setCursor(new Cursor(HAND_CURSOR) {
        });
        jbtChildManager.setCursor(new Cursor(HAND_CURSOR) {
        });
        jbtActivity.setCursor(new Cursor(HAND_CURSOR) {
        });
        jbtAdopters.setCursor(new Cursor(HAND_CURSOR) {
        });
        jbtEquipment.setCursor(new Cursor(HAND_CURSOR) {
        });
        jbtFeedback.setCursor(new Cursor(HAND_CURSOR) {
        });
        jbtIntroductor.setCursor(new Cursor(HAND_CURSOR) {
        });
        jbtSendNotification.setCursor(new Cursor(HAND_CURSOR) {
        });
        jbtExtracurricular.setCursor(new Cursor(HAND_CURSOR) {
        });
        jbtCharity.setCursor(new Cursor(HAND_CURSOR) {
        });
        jbtLogout.setCursor(new Cursor(HAND_CURSOR) {
        });
        jbtCacular.setCursor(new Cursor(HAND_CURSOR) {
        });
    }

    public void setMenuColor(JLabel choose) {
        jlb1.setBackground(new Color(255, 255, 255));
        jlb2.setBackground(new Color(255, 255, 255));
        jlb3.setBackground(new Color(255, 255, 255));
        jlb4.setBackground(new Color(255, 255, 255));
        jlb5.setBackground(new Color(255, 255, 255));
        jlb6.setBackground(new Color(255, 255, 255));
        jlb7.setBackground(new Color(255, 255, 255));
        jlb8.setBackground(new Color(255, 255, 255));
        jlb9.setBackground(new Color(255, 255, 255));
        choose.setBackground(new Color(102, 203, 254));

    }

    public void setShowMenu(JFrame jf) {
        jbtExtracurricular.setVisible(false);
        jbtCharity.setVisible(false);
        jbtSendStaff.setVisible(false);
        jbtSendmain.setVisible(false);
        staffManager.setVisible(false);
        childManager.setVisible(false);
        equipmentManager.setVisible(false);
        extracManager.setVisible(false);
        charityManager.setVisible(false);
        introManager.setVisible(false);
        StaffNotifi.setVisible(false);
        adop.setVisible(false);
        if (jf != null) {
            jf.setVisible(true);
        }
    }

    public ImageIcon ResizeImage(String ImagePath) {
        ImageIcon myImage = new ImageIcon(ImagePath);
        Image img = myImage.getImage();
        Image newImage = img.getScaledInstance(jlbIcon.getWidth(), jlbIcon.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImage);
        return image;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jpnName = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jlbNameStaff = new javax.swing.JLabel();
        jlbIcon = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jlb8 = new javax.swing.JLabel();
        jlb9 = new javax.swing.JLabel();
        jlb7 = new javax.swing.JLabel();
        jlb6 = new javax.swing.JLabel();
        jlb5 = new javax.swing.JLabel();
        jlb4 = new javax.swing.JLabel();
        jlb3 = new javax.swing.JLabel();
        jlb2 = new javax.swing.JLabel();
        jlb1 = new javax.swing.JLabel();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpnName.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jpnNameLayout = new javax.swing.GroupLayout(jpnName);
        jpnName.setLayout(jpnNameLayout);
        jpnNameLayout.setHorizontalGroup(
            jpnNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );
        jpnNameLayout.setVerticalGroup(
            jpnNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );

        jPanel1.add(jpnName, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 97, 280, 510));

        jPanel3.setBackground(new java.awt.Color(25, 118, 211));

        jlbNameStaff.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jlbNameStaff.setForeground(new java.awt.Color(255, 255, 255));
        jlbNameStaff.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jlbIcon.setBackground(new java.awt.Color(204, 204, 204));
        jlbIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbIcon.setToolTipText("");
        jlbIcon.setOpaque(true);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jlbIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbNameStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jlbNameStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
            .addComponent(jlbIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, 290, 90));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jlb8.setBackground(new java.awt.Color(102, 204, 255));
        jlb8.setOpaque(true);

        jlb9.setBackground(new java.awt.Color(102, 204, 255));
        jlb9.setOpaque(true);

        jlb7.setBackground(new java.awt.Color(102, 204, 255));
        jlb7.setOpaque(true);

        jlb6.setBackground(new java.awt.Color(102, 204, 255));
        jlb6.setOpaque(true);

        jlb5.setBackground(new java.awt.Color(102, 204, 255));
        jlb5.setOpaque(true);

        jlb4.setBackground(new java.awt.Color(102, 204, 255));
        jlb4.setOpaque(true);

        jlb3.setBackground(new java.awt.Color(102, 204, 255));
        jlb3.setOpaque(true);

        jlb2.setBackground(new java.awt.Color(102, 204, 255));
        jlb2.setOpaque(true);

        jlb1.setBackground(new java.awt.Color(102, 204, 255));
        jlb1.setOpaque(true);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jlb7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlb3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlb8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 10, Short.MAX_VALUE)
                    .addComponent(jlb9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 10, Short.MAX_VALUE)
                    .addComponent(jlb6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 10, Short.MAX_VALUE)
                    .addComponent(jlb5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 10, Short.MAX_VALUE)
                    .addComponent(jlb4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 10, Short.MAX_VALUE)
                    .addComponent(jlb2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 10, Short.MAX_VALUE)
                    .addComponent(jlb1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 10, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jlb1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlb2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlb3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlb4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlb5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlb6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jlb7, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlb8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlb9, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 10, 520));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1130, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1144, 701));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtStaffManagerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtStaffManagerMouseClicked
        setShowMenu(staffManager);
        staffManager.showListStaff();
        staffManager.setID_NVQL(ID_NVQL);
        setMenuColor(jlb1);

    }//GEN-LAST:event_jbtStaffManagerMouseClicked

    private void jbtChildManagerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtChildManagerMouseClicked
        setShowMenu(childManager);
        childManager.ShowChild(1);
        childManager.setID_NVQL(ID_NVQL);
        setMenuColor(jlb2);
    }//GEN-LAST:event_jbtChildManagerMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        setShowMenu(staffManager);
        staffManager.setID_NVQL(ID_NVQL);
        Vector<managementStaff> list = new Vector<>();
        list = admin.FindID(Integer.parseInt(ID_NVQL));
        jlbIcon.setIcon(ResizeImage("D:\\project\\TrungTamBaoTroTreEm\\DemoPBL\\src\\Img\\StaffManagement\\" + list.get(0).getImage()));
        jlbNameStaff.setText(staffManager.getNameNVQL());
    }//GEN-LAST:event_formWindowOpened

    private void jbtEquipmentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtEquipmentMouseClicked
        setShowMenu(equipmentManager);
        equipmentManager.ShowEquip(1);
        equipmentManager.setID_NVQL(ID_NVQL);
        setMenuColor(jlb3);
    }//GEN-LAST:event_jbtEquipmentMouseClicked

    private void jbtLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtLogoutActionPerformed

        this.setVisible(false);
        log.setVisible(true);
        setShowMenu(null);


    }//GEN-LAST:event_jbtLogoutActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        setShowMenu(null);
    }//GEN-LAST:event_formWindowClosed

    private void jbtActivityMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtActivityMouseClicked
        jbtExtracurricular.setVisible(true);
        jbtCharity.setVisible(true);
        setMenuColor(jlb4);
    }//GEN-LAST:event_jbtActivityMouseClicked

    private void jbtSendNotificationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtSendNotificationMouseClicked
        setMenuColor(jlb9);
        jbtSendStaff.setVisible(true);
        jbtSendmain.setVisible(true);
    }//GEN-LAST:event_jbtSendNotificationMouseClicked

    private void jbtIntroductorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtIntroductorMouseClicked
        setMenuColor(jlb5);
        setShowMenu(introManager);
        introManager.setID_NVQL(ID_NVQL);
    }//GEN-LAST:event_jbtIntroductorMouseClicked

    private void jbtCharityMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtCharityMouseClicked
        setShowMenu(charityManager);
        charityManager.setIDNVQL(ID_NVQL);
    }//GEN-LAST:event_jbtCharityMouseClicked

    private void jbtExtracurricularMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtExtracurricularMouseClicked
        setShowMenu(extracManager);
        extracManager.setIDNVQL(ID_NVQL);

    }//GEN-LAST:event_jbtExtracurricularMouseClicked

    private void jbtSendStaffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtSendStaffMouseClicked
        setShowMenu(StaffNotifi);
        StaffNotifi.setID_NVQL(ID_NVQL);
    }//GEN-LAST:event_jbtSendStaffMouseClicked

    private void jbtSendmainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtSendmainMouseClicked
        setShowMenu(News);
        News.setID_NVQL(ID_NVQL);
    }//GEN-LAST:event_jbtSendmainMouseClicked

    private void jbtAdoptersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtAdoptersMouseClicked
        setShowMenu(adop);
        setMenuColor(jlb6);
        adop.setID_NVQL(ID_NVQL);
    }//GEN-LAST:event_jbtAdoptersMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new staff().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel jlb1;
    private javax.swing.JLabel jlb2;
    private javax.swing.JLabel jlb3;
    private javax.swing.JLabel jlb4;
    private javax.swing.JLabel jlb5;
    private javax.swing.JLabel jlb6;
    private javax.swing.JLabel jlb7;
    private javax.swing.JLabel jlb8;
    private javax.swing.JLabel jlb9;
    private javax.swing.JLabel jlbIcon;
    private javax.swing.JLabel jlbNameStaff;
    private javax.swing.JPanel jpnName;
    // End of variables declaration//GEN-END:variables

    public JLabel getjlbNameStaff() {
        return jlbNameStaff;
    }

    public void setjlbNameStaff(String name) {
        this.jlbNameStaff.setText(name);
    }
}
