package view;

import controller.AdminListener;
import controller.StaffManagerListener;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Image;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import model.Adopter;
import model.managementStaff;
import view.NotificationToStaff.NotificationToStaff;
import view.NotificationToMainPage.NotificationToMainPage;
import view.viewStaffManager.AdopterManager;
import view.viewStaffManager.ExtracurricularActivities;
import view.viewStaffManager.CharityActivityManager;
import view.viewStaffManager.ChildrenManager;
import view.viewStaffManager.EquipmentManager;
import view.viewStaffManager.IntroductorManager;
import view.viewStaffManager.StaffManager;

public class staff extends javax.swing.JFrame {

    StaffManager staffManager = new StaffManager();
    EquipmentManager equipmentManager = new EquipmentManager();
    ChildrenManager childManager = new ChildrenManager();
    ExtracurricularActivities extracManager = new ExtracurricularActivities();
    CharityActivityManager charityManager = new CharityActivityManager();
    IntroductorManager introManager = new IntroductorManager();
    NotificationToStaff StaffNotifi = new NotificationToStaff();
    NotificationToMainPage News = new NotificationToMainPage();
    AdopterManager adop = new AdopterManager();
    Login log = new Login();
    AdminListener admin = new AdminListener();

    //get id to jlabel StaffName
    String ID_NVQL;

    public String getID_NVQL() {
        return ID_NVQL;
    }

    public void setID_NVQL(String ID_NVQL) {
        this.ID_NVQL = ID_NVQL;
    }

    /**
     * Creates new form staff
     */
    public staff() {
        staffManager.setVisible(true);
        initComponents();
        this.setExtendedState(this.MAXIMIZED_BOTH);
        setMenuColor(jlb1);
        jbtExtracurricular.setVisible(false);
        jbtCharity.setVisible(false);
        jbtSendStaff.setVisible(false);
        jbtSendmain.setVisible(false);
        setCursor();
    }

    public void setCursor() {
        jbtStaffManager.setCursor(new Cursor(HAND_CURSOR) {
        });
        jbtChildManager.setCursor(new Cursor(HAND_CURSOR) {
        });
        jbtActivity.setCursor(new Cursor(HAND_CURSOR) {
        });
        jbtAdopters.setCursor(new Cursor(HAND_CURSOR) {
        });
        jbtEquipment.setCursor(new Cursor(HAND_CURSOR) {
        });
        jbtFeedback.setCursor(new Cursor(HAND_CURSOR) {
        });
        jbtIntroductor.setCursor(new Cursor(HAND_CURSOR) {
        });
        jbtSendNotification.setCursor(new Cursor(HAND_CURSOR) {
        });
        jbtExtracurricular.setCursor(new Cursor(HAND_CURSOR) {
        });
        jbtCharity.setCursor(new Cursor(HAND_CURSOR) {
        });
        jbtLogout.setCursor(new Cursor(HAND_CURSOR) {
        });
        jbtCacular.setCursor(new Cursor(HAND_CURSOR) {
        });
    }

    public void setMenuColor(JLabel choose) {
        jlb1.setBackground(new Color(255, 255, 255));
        jlb2.setBackground(new Color(255, 255, 255));
        jlb3.setBackground(new Color(255, 255, 255));
        jlb4.setBackground(new Color(255, 255, 255));
        jlb5.setBackground(new Color(255, 255, 255));
        jlb6.setBackground(new Color(255, 255, 255));
        jlb7.setBackground(new Color(255, 255, 255));
        jlb8.setBackground(new Color(255, 255, 255));
        jlb9.setBackground(new Color(255, 255, 255));
        choose.setBackground(new Color(102, 203, 254));

    }

    public void setShowMenu(JFrame jf) {
        jbtExtracurricular.setVisible(false);
        jbtCharity.setVisible(false);
        jbtSendStaff.setVisible(false);
        jbtSendmain.setVisible(false);
        staffManager.setVisible(false);
        childManager.setVisible(false);
        equipmentManager.setVisible(false);
        extracManager.setVisible(false);
        charityManager.setVisible(false);
        introManager.setVisible(false);
        StaffNotifi.setVisible(false);
        News.setVisible(false);
        adop.setVisible(false);
        if (jf != null) {
            jf.setVisible(true);
        }
    }

    public ImageIcon ResizeImage(String ImagePath) {
        ImageIcon myImage = new ImageIcon(ImagePath);
        Image img = myImage.getImage();
        Image newImage = img.getScaledInstance(jlbIcon.getWidth(), jlbIcon.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImage);
        return image;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jpnName = new javax.swing.JPanel();
        jbtChildManager = new jbuttonCustom.JButtonCustom();
        jbtIntroductor = new jbuttonCustom.JButtonCustom();
        jbtActivity = new jbuttonCustom.JButtonCustom();
        jbtEquipment = new jbuttonCustom.JButtonCustom();
        jbtStaffManager = new jbuttonCustom.JButtonCustom();
        jbtAdopters = new jbuttonCustom.JButtonCustom();
        jbtFeedback = new jbuttonCustom.JButtonCustom();
        jbtCacular = new jbuttonCustom.JButtonCustom();
        jbtSendNotification = new jbuttonCustom.JButtonCustom();
        jPanel3 = new javax.swing.JPanel();
        jlbNameStaff = new javax.swing.JLabel();
        jlbIcon = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jlb8 = new javax.swing.JLabel();
        jlb9 = new javax.swing.JLabel();
        jlb7 = new javax.swing.JLabel();
        jlb6 = new javax.swing.JLabel();
        jlb5 = new javax.swing.JLabel();
        jlb4 = new javax.swing.JLabel();
        jlb3 = new javax.swing.JLabel();
        jlb2 = new javax.swing.JLabel();
        jlb1 = new javax.swing.JLabel();
        jbtLogout = new jbuttonCustom.JButtonCustom();
        jbtCharity = new jbuttonCustom.JButtonCustom();
        jbtExtracurricular = new jbuttonCustom.JButtonCustom();
        jbtSendStaff = new jbuttonCustom.JButtonCustom();
        jbtSendmain = new jbuttonCustom.JButtonCustom();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpnName.setBackground(new java.awt.Color(255, 255, 255));

        jbtChildManager.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jbtChildManager.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ảnh/baby.png"))); // NOI18N
        jbtChildManager.setText("  Quản lý trẻ ");
        jbtChildManager.setBoderColor(new java.awt.Color(255, 255, 255));
        jbtChildManager.setColoOver(new java.awt.Color(255, 255, 0));
        jbtChildManager.setColorClick(new java.awt.Color(102, 255, 51));
        jbtChildManager.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        jbtChildManager.setDisabledIcon(null);
        jbtChildManager.setDisabledSelectedIcon(null);
        jbtChildManager.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jbtChildManager.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbtChildManager.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jbtChildManager.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtChildManagerMouseClicked(evt);
            }
        });

        jbtIntroductor.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jbtIntroductor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ảnh/icons8_people_50px.png"))); // NOI18N
        jbtIntroductor.setText("Quản Lý Người Giới Thiệu");
        jbtIntroductor.setBoderColor(new java.awt.Color(255, 255, 255));
        jbtIntroductor.setColoOver(new java.awt.Color(255, 255, 0));
        jbtIntroductor.setColorClick(new java.awt.Color(102, 255, 51));
        jbtIntroductor.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        jbtIntroductor.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jbtIntroductor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbtIntroductor.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jbtIntroductor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtIntroductorMouseClicked(evt);
            }
        });

        jbtActivity.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jbtActivity.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ảnh/icons8_strike_40px.png"))); // NOI18N
        jbtActivity.setText("Quản lý hoạt động");
        jbtActivity.setBoderColor(new java.awt.Color(255, 255, 255));
        jbtActivity.setColoOver(new java.awt.Color(255, 255, 0));
        jbtActivity.setColorClick(new java.awt.Color(102, 255, 51));
        jbtActivity.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        jbtActivity.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jbtActivity.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbtActivity.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jbtActivity.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtActivityMouseClicked(evt);
            }
        });

        jbtEquipment.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jbtEquipment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ảnh/icons8_touchpad_48px.png"))); // NOI18N
        jbtEquipment.setText("Quản lý thiết bị");
        jbtEquipment.setBoderColor(new java.awt.Color(255, 255, 255));
        jbtEquipment.setColoOver(new java.awt.Color(255, 255, 0));
        jbtEquipment.setColorClick(new java.awt.Color(102, 255, 51));
        jbtEquipment.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        jbtEquipment.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jbtEquipment.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbtEquipment.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jbtEquipment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtEquipmentMouseClicked(evt);
            }
        });

        jbtStaffManager.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jbtStaffManager.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ảnh/icons8_people_50px.png"))); // NOI18N
        jbtStaffManager.setText("Quản lý Cán Bộ");
        jbtStaffManager.setBoderColor(new java.awt.Color(255, 255, 255));
        jbtStaffManager.setColoOver(new java.awt.Color(255, 255, 0));
        jbtStaffManager.setColorClick(new java.awt.Color(102, 255, 51));
        jbtStaffManager.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        jbtStaffManager.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jbtStaffManager.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbtStaffManager.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jbtStaffManager.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtStaffManagerMouseClicked(evt);
            }
        });

        jbtAdopters.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jbtAdopters.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ảnh/icons8_people_50px.png"))); // NOI18N
        jbtAdopters.setText("Quản Lý Người Nhận Nuôi");
        jbtAdopters.setBoderColor(new java.awt.Color(255, 255, 255));
        jbtAdopters.setColoOver(new java.awt.Color(255, 255, 0));
        jbtAdopters.setColorClick(new java.awt.Color(102, 255, 51));
        jbtAdopters.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        jbtAdopters.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jbtAdopters.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbtAdopters.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jbtAdopters.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtAdoptersMouseClicked(evt);
            }
        });

        jbtFeedback.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jbtFeedback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/feedback_48px.png"))); // NOI18N
        jbtFeedback.setText("     Quản lý phản hồi      ");
        jbtFeedback.setAutoscrolls(true);
        jbtFeedback.setBoderColor(new java.awt.Color(255, 255, 255));
        jbtFeedback.setColoOver(new java.awt.Color(255, 255, 0));
        jbtFeedback.setColorClick(new java.awt.Color(102, 255, 51));
        jbtFeedback.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        jbtFeedback.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jbtFeedback.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbtFeedback.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jbtCacular.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jbtCacular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ảnh/icons8_search_property_38px_1.png"))); // NOI18N
        jbtCacular.setText("  Thống kê, tìm kiếm");
        jbtCacular.setBoderColor(new java.awt.Color(255, 255, 255));
        jbtCacular.setColoOver(new java.awt.Color(255, 255, 0));
        jbtCacular.setColorClick(new java.awt.Color(102, 255, 51));
        jbtCacular.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        jbtCacular.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jbtCacular.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbtCacular.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jbtSendNotification.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jbtSendNotification.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/notification_48px.png"))); // NOI18N
        jbtSendNotification.setText("Gửi thông báo");
        jbtSendNotification.setBoderColor(new java.awt.Color(255, 255, 255));
        jbtSendNotification.setColoOver(new java.awt.Color(255, 255, 0));
        jbtSendNotification.setColorClick(new java.awt.Color(102, 255, 51));
        jbtSendNotification.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        jbtSendNotification.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jbtSendNotification.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbtSendNotification.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jbtSendNotification.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtSendNotificationMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpnNameLayout = new javax.swing.GroupLayout(jpnName);
        jpnName.setLayout(jpnNameLayout);
        jpnNameLayout.setHorizontalGroup(
            jpnNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jbtEquipment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jbtStaffManager, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpnNameLayout.createSequentialGroup()
                .addGroup(jpnNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtFeedback, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtCacular, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtChildManager, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtSendNotification, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtAdopters, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jpnNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                .addComponent(jbtActivity, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtIntroductor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE))
        );
        jpnNameLayout.setVerticalGroup(
            jpnNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnNameLayout.createSequentialGroup()
                .addGroup(jpnNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnNameLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jbtEquipment, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jbtStaffManager, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpnNameLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jbtChildManager, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpnNameLayout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jbtActivity, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(1, 1, 1)
                .addComponent(jbtIntroductor, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtAdopters, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtFeedback, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtCacular, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtSendNotification, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jpnName, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 97, 280, 510));

        jPanel3.setBackground(new java.awt.Color(25, 118, 211));

        jlbNameStaff.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jlbNameStaff.setForeground(new java.awt.Color(255, 255, 255));
        jlbNameStaff.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jlbIcon.setBackground(new java.awt.Color(204, 204, 204));
        jlbIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbIcon.setToolTipText("");
        jlbIcon.setOpaque(true);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jlbIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbNameStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jlbNameStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
            .addComponent(jlbIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, 290, 90));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jlb8.setBackground(new java.awt.Color(102, 204, 255));
        jlb8.setOpaque(true);

        jlb9.setBackground(new java.awt.Color(102, 204, 255));
        jlb9.setOpaque(true);

        jlb7.setBackground(new java.awt.Color(102, 204, 255));
        jlb7.setOpaque(true);

        jlb6.setBackground(new java.awt.Color(102, 204, 255));
        jlb6.setOpaque(true);

        jlb5.setBackground(new java.awt.Color(102, 204, 255));
        jlb5.setOpaque(true);

        jlb4.setBackground(new java.awt.Color(102, 204, 255));
        jlb4.setOpaque(true);

        jlb3.setBackground(new java.awt.Color(102, 204, 255));
        jlb3.setOpaque(true);

        jlb2.setBackground(new java.awt.Color(102, 204, 255));
        jlb2.setOpaque(true);

        jlb1.setBackground(new java.awt.Color(102, 204, 255));
        jlb1.setOpaque(true);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jlb7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlb3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlb8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 10, Short.MAX_VALUE)
                    .addComponent(jlb9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 10, Short.MAX_VALUE)
                    .addComponent(jlb6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 10, Short.MAX_VALUE)
                    .addComponent(jlb5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 10, Short.MAX_VALUE)
                    .addComponent(jlb4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 10, Short.MAX_VALUE)
                    .addComponent(jlb2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 10, Short.MAX_VALUE)
                    .addComponent(jlb1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 10, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jlb1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlb2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlb3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlb4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlb5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlb6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jlb7, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlb8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlb9, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 10, 520));

        jbtLogout.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jbtLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/sign_out_24px.png"))); // NOI18N
        jbtLogout.setText("Đăng Xuất");
        jbtLogout.setBoderColor(new java.awt.Color(255, 255, 255));
        jbtLogout.setColoOver(new java.awt.Color(255, 255, 0));
        jbtLogout.setColorClick(new java.awt.Color(102, 255, 51));
        jbtLogout.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        jbtLogout.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jbtLogout.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jbtLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtLogoutActionPerformed(evt);
            }
        });
        jPanel1.add(jbtLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 640, 271, 44));

        jbtCharity.setBackground(new java.awt.Color(204, 255, 255));
        jbtCharity.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jbtCharity.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/handshake_heart_48px.png"))); // NOI18N
        jbtCharity.setText("Hoạt động từ thiện");
        jbtCharity.setBoderColor(new java.awt.Color(255, 255, 255));
        jbtCharity.setColoOver(new java.awt.Color(255, 255, 0));
        jbtCharity.setColorClick(new java.awt.Color(102, 255, 51));
        jbtCharity.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        jbtCharity.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jbtCharity.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbtCharity.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jbtCharity.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtCharityMouseClicked(evt);
            }
        });
        jPanel1.add(jbtCharity, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, 230, 50));

        jbtExtracurricular.setBackground(new java.awt.Color(204, 255, 255));
        jbtExtracurricular.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jbtExtracurricular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/pullups_50px.png"))); // NOI18N
        jbtExtracurricular.setText("Hoạt động ngoại khoá");
        jbtExtracurricular.setBoderColor(new java.awt.Color(255, 255, 255));
        jbtExtracurricular.setColoOver(new java.awt.Color(255, 255, 0));
        jbtExtracurricular.setColorClick(new java.awt.Color(102, 255, 51));
        jbtExtracurricular.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        jbtExtracurricular.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jbtExtracurricular.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbtExtracurricular.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jbtExtracurricular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtExtracurricularMouseClicked(evt);
            }
        });
        jPanel1.add(jbtExtracurricular, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 230, -1));

        jbtSendStaff.setBackground(new java.awt.Color(204, 255, 255));
        jbtSendStaff.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jbtSendStaff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/handshake_heart_48px.png"))); // NOI18N
        jbtSendStaff.setText("Gửi cho cán bộ nhân viên");
        jbtSendStaff.setBoderColor(new java.awt.Color(255, 255, 255));
        jbtSendStaff.setColoOver(new java.awt.Color(255, 255, 0));
        jbtSendStaff.setColorClick(new java.awt.Color(102, 255, 51));
        jbtSendStaff.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        jbtSendStaff.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jbtSendStaff.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbtSendStaff.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jbtSendStaff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtSendStaffMouseClicked(evt);
            }
        });
        jPanel1.add(jbtSendStaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 570, 260, 50));

        jbtSendmain.setBackground(new java.awt.Color(204, 255, 255));
        jbtSendmain.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jbtSendmain.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/pullups_50px.png"))); // NOI18N
        jbtSendmain.setText("Đưa ra trang chủ");
        jbtSendmain.setBoderColor(new java.awt.Color(255, 255, 255));
        jbtSendmain.setColoOver(new java.awt.Color(255, 255, 0));
        jbtSendmain.setColorClick(new java.awt.Color(102, 255, 51));
        jbtSendmain.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        jbtSendmain.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jbtSendmain.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbtSendmain.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jbtSendmain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtSendmainMouseClicked(evt);
            }
        });
        jPanel1.add(jbtSendmain, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 520, 260, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1130, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1144, 701));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtStaffManagerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtStaffManagerMouseClicked
        setShowMenu(staffManager);
        staffManager.showListStaff(1);
        staffManager.setID_NVQL(ID_NVQL);
        setMenuColor(jlb1);

    }//GEN-LAST:event_jbtStaffManagerMouseClicked

    private void jbtChildManagerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtChildManagerMouseClicked
        setShowMenu(childManager);
        childManager.ShowChild(1);
        childManager.setID_NVQL(ID_NVQL);
        setMenuColor(jlb2);
    }//GEN-LAST:event_jbtChildManagerMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        setShowMenu(staffManager);
        staffManager.setID_NVQL(ID_NVQL);
        ArrayList<managementStaff> list = new ArrayList<>();
        list = admin.FindID((ID_NVQL));
        jlbIcon.setIcon(ResizeImage("D:\\project\\TrungTamBaoTroTreEm\\DemoPBL\\src\\Img\\StaffManagement\\" + list.get(0).getImage()));
        jlbNameStaff.setText(staffManager.getNameNVQL());
    }//GEN-LAST:event_formWindowOpened

    private void jbtEquipmentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtEquipmentMouseClicked
        setShowMenu(equipmentManager);
        equipmentManager.ShowEquip(1);
        equipmentManager.setID_NVQL(ID_NVQL);
        setMenuColor(jlb3);
    }//GEN-LAST:event_jbtEquipmentMouseClicked

    private void jbtLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtLogoutActionPerformed

        this.setVisible(false);
        log.setVisible(true);
        setShowMenu(null);


    }//GEN-LAST:event_jbtLogoutActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        setShowMenu(null);
    }//GEN-LAST:event_formWindowClosed

    private void jbtActivityMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtActivityMouseClicked
        jbtExtracurricular.setVisible(true);
        jbtCharity.setVisible(true);
        setMenuColor(jlb4);
    }//GEN-LAST:event_jbtActivityMouseClicked

    private void jbtSendNotificationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtSendNotificationMouseClicked
        setMenuColor(jlb9);
        jbtSendStaff.setVisible(true);
        jbtSendmain.setVisible(true);
    }//GEN-LAST:event_jbtSendNotificationMouseClicked

    private void jbtIntroductorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtIntroductorMouseClicked
        setMenuColor(jlb5);
        setShowMenu(introManager);
        introManager.setID_NVQL(ID_NVQL);
    }//GEN-LAST:event_jbtIntroductorMouseClicked

    private void jbtCharityMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtCharityMouseClicked
        setShowMenu(charityManager);
        charityManager.setIDNVQL(ID_NVQL);
    }//GEN-LAST:event_jbtCharityMouseClicked

    private void jbtExtracurricularMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtExtracurricularMouseClicked
        setShowMenu(extracManager);
        extracManager.setIDNVQL(ID_NVQL);

    }//GEN-LAST:event_jbtExtracurricularMouseClicked

    private void jbtSendStaffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtSendStaffMouseClicked
        setShowMenu(StaffNotifi);
        StaffNotifi.setID_NVQL(ID_NVQL);
    }//GEN-LAST:event_jbtSendStaffMouseClicked

    private void jbtSendmainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtSendmainMouseClicked
        setShowMenu(News);
        News.setID_NVQL(ID_NVQL);
    }//GEN-LAST:event_jbtSendmainMouseClicked

    private void jbtAdoptersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtAdoptersMouseClicked
        setShowMenu(adop);
        setMenuColor(jlb6);
        adop.setID_NVQL(ID_NVQL);
    }//GEN-LAST:event_jbtAdoptersMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new staff().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private jbuttonCustom.JButtonCustom jbtActivity;
    private jbuttonCustom.JButtonCustom jbtAdopters;
    private jbuttonCustom.JButtonCustom jbtCacular;
    private jbuttonCustom.JButtonCustom jbtCharity;
    private jbuttonCustom.JButtonCustom jbtChildManager;
    private jbuttonCustom.JButtonCustom jbtEquipment;
    private jbuttonCustom.JButtonCustom jbtExtracurricular;
    private jbuttonCustom.JButtonCustom jbtFeedback;
    private jbuttonCustom.JButtonCustom jbtIntroductor;
    private jbuttonCustom.JButtonCustom jbtLogout;
    private jbuttonCustom.JButtonCustom jbtSendNotification;
    private jbuttonCustom.JButtonCustom jbtSendStaff;
    private jbuttonCustom.JButtonCustom jbtSendmain;
    private jbuttonCustom.JButtonCustom jbtStaffManager;
    private javax.swing.JLabel jlb1;
    private javax.swing.JLabel jlb2;
    private javax.swing.JLabel jlb3;
    private javax.swing.JLabel jlb4;
    private javax.swing.JLabel jlb5;
    private javax.swing.JLabel jlb6;
    private javax.swing.JLabel jlb7;
    private javax.swing.JLabel jlb8;
    private javax.swing.JLabel jlb9;
    private javax.swing.JLabel jlbIcon;
    private javax.swing.JLabel jlbNameStaff;
    private javax.swing.JPanel jpnName;
    // End of variables declaration//GEN-END:variables

    public JLabel getjlbNameStaff() {
        return jlbNameStaff;
    }

    public void setjlbNameStaff(String name) {
        this.jlbNameStaff.setText(name);
    }
}
