package view;

import controller.SendID_NVQL;
import controller.StaffManagerListener;
import java.awt.Color;
import java.awt.Cursor;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import view.viewStaffManager.ChildrenManager;
import view.viewStaffManager.EquipmentManager;
import view.viewStaffManager.StaffManager;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author QUOC KHANH
 */
public class staff extends javax.swing.JFrame {

    StaffManager staffManager = new StaffManager();
    EquipmentManager equipmentManager = new EquipmentManager();
    ChildrenManager childManager = new ChildrenManager();
    Login log = new Login();

    //get id to jlabel StaffName
    String ID_NVQL;

    public String getID_NVQL() {
        return ID_NVQL;
    }

    public void setID_NVQL(String ID_NVQL) {
        this.ID_NVQL = ID_NVQL;
    }

    /**
     * Creates new form staff
     */
    public staff() {
        staffManager.setVisible(true);
        initComponents();
        this.setExtendedState(this.MAXIMIZED_BOTH);
        setMenuColor(jlb1);
    }

    public void setMenuColor(JLabel choose) {
        jlb1.setBackground(new Color(255, 255, 255));
        jlb2.setBackground(new Color(255, 255, 255));
        jlb3.setBackground(new Color(255, 255, 255));
        jlb4.setBackground(new Color(255, 255, 255));
        jlb5.setBackground(new Color(255, 255, 255));
        jlb6.setBackground(new Color(255, 255, 255));
        jlb7.setBackground(new Color(255, 255, 255));
        jlb8.setBackground(new Color(255, 255, 255));
        jlb9.setBackground(new Color(255, 255, 255));
        choose.setBackground(new Color(102, 203, 254));

    }

    public void setShowMenu(JFrame jf) {
        staffManager.setVisible(false);
        childManager.setVisible(false);
        equipmentManager.setVisible(false);
        jf.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jpnName = new javax.swing.JPanel();
        jbtChildManager = new juttonCustom.JButtonCustom();
        jbtIntroductor = new juttonCustom.JButtonCustom();
        jbtActivity = new juttonCustom.JButtonCustom();
        jbtEquipment = new juttonCustom.JButtonCustom();
        jbtStaffManager = new juttonCustom.JButtonCustom();
        jbtAdopters = new juttonCustom.JButtonCustom();
        jbtFeedback = new juttonCustom.JButtonCustom();
        jbtCacular = new juttonCustom.JButtonCustom();
        jbtSendNotification = new juttonCustom.JButtonCustom();
        jPanel3 = new javax.swing.JPanel();
        jlbNameStaff = new javax.swing.JLabel();
        jlbIcon = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jlb9 = new javax.swing.JLabel();
        jlb1 = new javax.swing.JLabel();
        jlb2 = new javax.swing.JLabel();
        jlb3 = new javax.swing.JLabel();
        jlb4 = new javax.swing.JLabel();
        jlb5 = new javax.swing.JLabel();
        jlb6 = new javax.swing.JLabel();
        jlb7 = new javax.swing.JLabel();
        jlb8 = new javax.swing.JLabel();
        jbtLogout = new juttonCustom.JButtonCustom();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpnName.setBackground(new java.awt.Color(255, 255, 255));

        jbtChildManager.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jbtChildManager.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ảnh/baby.png"))); // NOI18N
        jbtChildManager.setText("  Quản lý trẻ ");
        jbtChildManager.setBoderColor(new java.awt.Color(255, 255, 255));
        jbtChildManager.setColoOver(new java.awt.Color(255, 255, 0));
        jbtChildManager.setColorClick(new java.awt.Color(102, 255, 51));
        jbtChildManager.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        jbtChildManager.setDisabledIcon(null);
        jbtChildManager.setDisabledSelectedIcon(null);
        jbtChildManager.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jbtChildManager.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbtChildManager.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jbtChildManager.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtChildManagerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtChildManagerMouseEntered(evt);
            }
        });
        jbtChildManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtChildManagerActionPerformed(evt);
            }
        });

        jbtIntroductor.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jbtIntroductor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ảnh/icons8_people_50px.png"))); // NOI18N
        jbtIntroductor.setText("Quản Lý Người Giới Thiệu");
        jbtIntroductor.setBoderColor(new java.awt.Color(255, 255, 255));
        jbtIntroductor.setColoOver(new java.awt.Color(255, 255, 0));
        jbtIntroductor.setColorClick(new java.awt.Color(102, 255, 51));
        jbtIntroductor.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        jbtIntroductor.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jbtIntroductor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbtIntroductor.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jbtIntroductor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtIntroductorMouseEntered(evt);
            }
        });

        jbtActivity.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jbtActivity.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ảnh/icons8_strike_40px.png"))); // NOI18N
        jbtActivity.setText("Quản lý hoạt động");
        jbtActivity.setBoderColor(new java.awt.Color(255, 255, 255));
        jbtActivity.setColoOver(new java.awt.Color(255, 255, 0));
        jbtActivity.setColorClick(new java.awt.Color(102, 255, 51));
        jbtActivity.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        jbtActivity.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jbtActivity.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbtActivity.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jbtActivity.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtActivityMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtActivityMouseEntered(evt);
            }
        });

        jbtEquipment.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jbtEquipment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ảnh/icons8_touchpad_48px.png"))); // NOI18N
        jbtEquipment.setText("Quản lý thiết bị");
        jbtEquipment.setBoderColor(new java.awt.Color(255, 255, 255));
        jbtEquipment.setColoOver(new java.awt.Color(255, 255, 0));
        jbtEquipment.setColorClick(new java.awt.Color(102, 255, 51));
        jbtEquipment.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        jbtEquipment.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jbtEquipment.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbtEquipment.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jbtEquipment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtEquipmentMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtEquipmentMouseEntered(evt);
            }
        });
        jbtEquipment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtEquipmentActionPerformed(evt);
            }
        });

        jbtStaffManager.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jbtStaffManager.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ảnh/icons8_people_50px.png"))); // NOI18N
        jbtStaffManager.setText("Quản lý Cán Bộ");
        jbtStaffManager.setBoderColor(new java.awt.Color(255, 255, 255));
        jbtStaffManager.setColoOver(new java.awt.Color(255, 255, 0));
        jbtStaffManager.setColorClick(new java.awt.Color(102, 255, 51));
        jbtStaffManager.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        jbtStaffManager.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jbtStaffManager.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbtStaffManager.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jbtStaffManager.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtStaffManagerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtStaffManagerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtStaffManagerMouseExited(evt);
            }
        });

        jbtAdopters.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jbtAdopters.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ảnh/icons8_people_50px.png"))); // NOI18N
        jbtAdopters.setText("Quản Lý Người Nhận Nuôi");
        jbtAdopters.setBoderColor(new java.awt.Color(255, 255, 255));
        jbtAdopters.setColoOver(new java.awt.Color(255, 255, 0));
        jbtAdopters.setColorClick(new java.awt.Color(102, 255, 51));
        jbtAdopters.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        jbtAdopters.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jbtAdopters.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbtAdopters.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jbtAdopters.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtAdoptersMouseEntered(evt);
            }
        });
        jbtAdopters.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtAdoptersActionPerformed(evt);
            }
        });

        jbtFeedback.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jbtFeedback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ảnh/icons8_feedback_26px.png"))); // NOI18N
        jbtFeedback.setText("     Quản lý phản hồi      ");
        jbtFeedback.setAutoscrolls(true);
        jbtFeedback.setBoderColor(new java.awt.Color(255, 255, 255));
        jbtFeedback.setColoOver(new java.awt.Color(255, 255, 0));
        jbtFeedback.setColorClick(new java.awt.Color(102, 255, 51));
        jbtFeedback.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        jbtFeedback.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jbtFeedback.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbtFeedback.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jbtFeedback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtFeedbackMouseEntered(evt);
            }
        });
        jbtFeedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtFeedbackActionPerformed(evt);
            }
        });

        jbtCacular.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jbtCacular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ảnh/icons8_search_property_38px_1.png"))); // NOI18N
        jbtCacular.setText("  Thống kê, tìm kiếm");
        jbtCacular.setBoderColor(new java.awt.Color(255, 255, 255));
        jbtCacular.setColoOver(new java.awt.Color(255, 255, 0));
        jbtCacular.setColorClick(new java.awt.Color(102, 255, 51));
        jbtCacular.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        jbtCacular.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jbtCacular.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbtCacular.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jbtCacular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtCacularMouseEntered(evt);
            }
        });

        jbtSendNotification.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jbtSendNotification.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ảnh/icons8_notification_48px.png"))); // NOI18N
        jbtSendNotification.setText("Gửi thông báo");
        jbtSendNotification.setBoderColor(new java.awt.Color(255, 255, 255));
        jbtSendNotification.setColoOver(new java.awt.Color(255, 255, 0));
        jbtSendNotification.setColorClick(new java.awt.Color(102, 255, 51));
        jbtSendNotification.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        jbtSendNotification.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jbtSendNotification.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbtSendNotification.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jbtSendNotification.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtSendNotificationMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtSendNotificationMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtSendNotificationMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jpnNameLayout = new javax.swing.GroupLayout(jpnName);
        jpnName.setLayout(jpnNameLayout);
        jpnNameLayout.setHorizontalGroup(
            jpnNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jbtActivity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jbtEquipment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jbtStaffManager, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpnNameLayout.createSequentialGroup()
                .addComponent(jbtIntroductor, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jpnNameLayout.createSequentialGroup()
                .addGroup(jpnNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtFeedback, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtCacular, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtChildManager, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtSendNotification, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtAdopters, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpnNameLayout.setVerticalGroup(
            jpnNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnNameLayout.createSequentialGroup()
                .addGroup(jpnNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnNameLayout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jbtActivity, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpnNameLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jbtEquipment, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jbtStaffManager, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpnNameLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jbtChildManager, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(1, 1, 1)
                .addComponent(jbtIntroductor, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtAdopters, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtFeedback, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtCacular, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtSendNotification, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jpnName, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 97, 280, 510));

        jPanel3.setBackground(new java.awt.Color(25, 118, 211));

        jlbNameStaff.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jlbNameStaff.setForeground(new java.awt.Color(255, 255, 255));
        jlbNameStaff.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jlbIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbIcon.setToolTipText("");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jlbIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbNameStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jlbNameStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
            .addComponent(jlbIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, 290, 90));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jlb9.setBackground(new java.awt.Color(102, 204, 255));
        jlb9.setOpaque(true);

        jlb1.setBackground(new java.awt.Color(102, 204, 255));
        jlb1.setOpaque(true);

        jlb2.setBackground(new java.awt.Color(102, 204, 255));
        jlb2.setOpaque(true);

        jlb3.setBackground(new java.awt.Color(102, 204, 255));
        jlb3.setOpaque(true);

        jlb4.setBackground(new java.awt.Color(102, 204, 255));
        jlb4.setOpaque(true);

        jlb5.setBackground(new java.awt.Color(102, 204, 255));
        jlb5.setOpaque(true);

        jlb6.setBackground(new java.awt.Color(102, 204, 255));
        jlb6.setOpaque(true);

        jlb7.setBackground(new java.awt.Color(102, 204, 255));
        jlb7.setOpaque(true);

        jlb8.setBackground(new java.awt.Color(102, 204, 255));
        jlb8.setOpaque(true);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlb8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlb1, javax.swing.GroupLayout.DEFAULT_SIZE, 10, Short.MAX_VALUE)
                    .addComponent(jlb2, javax.swing.GroupLayout.DEFAULT_SIZE, 10, Short.MAX_VALUE)
                    .addComponent(jlb3, javax.swing.GroupLayout.DEFAULT_SIZE, 10, Short.MAX_VALUE)
                    .addComponent(jlb4, javax.swing.GroupLayout.DEFAULT_SIZE, 10, Short.MAX_VALUE)
                    .addComponent(jlb6, javax.swing.GroupLayout.DEFAULT_SIZE, 10, Short.MAX_VALUE)
                    .addComponent(jlb7, javax.swing.GroupLayout.DEFAULT_SIZE, 10, Short.MAX_VALUE)
                    .addComponent(jlb9, javax.swing.GroupLayout.DEFAULT_SIZE, 10, Short.MAX_VALUE)
                    .addComponent(jlb5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jlb1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jlb2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jlb3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jlb4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jlb5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlb6, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlb7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlb8, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlb9, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 10, 540));

        jbtLogout.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jbtLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/sign_out_24px.png"))); // NOI18N
        jbtLogout.setText("Đăng Xuất");
        jbtLogout.setBoderColor(new java.awt.Color(255, 255, 255));
        jbtLogout.setColoOver(new java.awt.Color(255, 255, 0));
        jbtLogout.setColorClick(new java.awt.Color(102, 255, 51));
        jbtLogout.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        jbtLogout.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jbtLogout.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jbtLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtLogoutActionPerformed(evt);
            }
        });
        jPanel1.add(jbtLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 640, 271, 44));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 694, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1144, 701));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtFeedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtFeedbackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtFeedbackActionPerformed

    private void jbtEquipmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtEquipmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtEquipmentActionPerformed

    private void jbtChildManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtChildManagerActionPerformed

    }//GEN-LAST:event_jbtChildManagerActionPerformed

    private void jbtAdoptersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtAdoptersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtAdoptersActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:


    }//GEN-LAST:event_formWindowActivated

    private void jbtStaffManagerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtStaffManagerMouseClicked
        setShowMenu(staffManager);
        staffManager.showListStaff();
        staffManager.setID_NVQL(ID_NVQL);
        setMenuColor(jlb1);

    }//GEN-LAST:event_jbtStaffManagerMouseClicked

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown

    }//GEN-LAST:event_formComponentShown

    private void jbtStaffManagerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtStaffManagerMouseEntered
        jbtStaffManager.setCursor(new Cursor(HAND_CURSOR) {
        });
//       jbtStaffManager.setBackground(new Color(255,255,0));
    }//GEN-LAST:event_jbtStaffManagerMouseEntered

    private void jbtStaffManagerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtStaffManagerMouseExited
        // TODO add your handling code here:
//        jbtStaffManager.setBackground(new Color(255,255,0));
    }//GEN-LAST:event_jbtStaffManagerMouseExited

    private void jbtChildManagerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtChildManagerMouseClicked
        setShowMenu(childManager);
        childManager.ShowListChild();
        childManager.setID_NVQL(ID_NVQL);
        setMenuColor(jlb2);
    }//GEN-LAST:event_jbtChildManagerMouseClicked

    // Open new JFrame when thecorresponding button is clicked
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        setShowMenu(staffManager);
        staffManager.setID_NVQL(ID_NVQL);
        jlbNameStaff.setText(ID_NVQL + "-" + staffManager.getNameNVQL());
    }//GEN-LAST:event_formWindowOpened

    private void jbtEquipmentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtEquipmentMouseClicked
        setShowMenu(equipmentManager);
        equipmentManager.ShowListEquip();
        equipmentManager.setID_NVQL(ID_NVQL);
        setMenuColor(jlb3);
    }//GEN-LAST:event_jbtEquipmentMouseClicked

    private void jbtChildManagerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtChildManagerMouseEntered
        jbtChildManager.setCursor(new Cursor(HAND_CURSOR) {
        });
    }//GEN-LAST:event_jbtChildManagerMouseEntered

    //Change cursor when mouseEnter button
    private void jbtEquipmentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtEquipmentMouseEntered
        jbtEquipment.setCursor(new Cursor(HAND_CURSOR) {
        });
    }//GEN-LAST:event_jbtEquipmentMouseEntered

    private void jbtActivityMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtActivityMouseEntered
        jbtActivity.setCursor(new Cursor(HAND_CURSOR) {
        });
    }//GEN-LAST:event_jbtActivityMouseEntered

    private void jbtLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtLogoutActionPerformed
        jbtLogout.setCursor(new Cursor(HAND_CURSOR) {
        });
        this.setVisible(false);
        log.setVisible(true);

    }//GEN-LAST:event_jbtLogoutActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        staffManager.setVisible(false);
    }//GEN-LAST:event_formWindowClosed

    private void jbtActivityMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtActivityMouseClicked

    }//GEN-LAST:event_jbtActivityMouseClicked

    private void jbtIntroductorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtIntroductorMouseEntered
        jbtIntroductor.setCursor(new Cursor(HAND_CURSOR) {
        });
    }//GEN-LAST:event_jbtIntroductorMouseEntered

    private void jbtAdoptersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtAdoptersMouseEntered
        jbtAdopters.setCursor(new Cursor(HAND_CURSOR) {
        });
    }//GEN-LAST:event_jbtAdoptersMouseEntered

    private void jbtFeedbackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtFeedbackMouseEntered
        jbtFeedback.setCursor(new Cursor(HAND_CURSOR) {
        });        
    }//GEN-LAST:event_jbtFeedbackMouseEntered

    private void jbtCacularMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtCacularMouseEntered
        jbtCacular.setCursor(new Cursor(HAND_CURSOR) {
        }); 
    }//GEN-LAST:event_jbtCacularMouseEntered

    private void jbtSendNotificationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtSendNotificationMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtSendNotificationMouseClicked

    private void jbtSendNotificationMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtSendNotificationMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtSendNotificationMouseExited

    private void jbtSendNotificationMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtSendNotificationMouseEntered
        jbtSendNotification.setCursor(new Cursor(HAND_CURSOR) {
        }); 
    }//GEN-LAST:event_jbtSendNotificationMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new staff().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private juttonCustom.JButtonCustom jbtActivity;
    private juttonCustom.JButtonCustom jbtAdopters;
    private juttonCustom.JButtonCustom jbtCacular;
    private juttonCustom.JButtonCustom jbtChildManager;
    private juttonCustom.JButtonCustom jbtEquipment;
    private juttonCustom.JButtonCustom jbtFeedback;
    private juttonCustom.JButtonCustom jbtIntroductor;
    private juttonCustom.JButtonCustom jbtLogout;
    private juttonCustom.JButtonCustom jbtSendNotification;
    private juttonCustom.JButtonCustom jbtStaffManager;
    private javax.swing.JLabel jlb1;
    private javax.swing.JLabel jlb2;
    private javax.swing.JLabel jlb3;
    private javax.swing.JLabel jlb4;
    private javax.swing.JLabel jlb5;
    private javax.swing.JLabel jlb6;
    private javax.swing.JLabel jlb7;
    private javax.swing.JLabel jlb8;
    private javax.swing.JLabel jlb9;
    private javax.swing.JLabel jlbIcon;
    private javax.swing.JLabel jlbNameStaff;
    private javax.swing.JPanel jpnName;
    // End of variables declaration//GEN-END:variables

    public JLabel getjlbNameStaff() {
        return jlbNameStaff;
    }

    public void setjlbNameStaff(String name) {
        this.jlbNameStaff.setText(name);
    }
}
