/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.viewStaffManager;

/**
 *
 * @author ADMIN
 */
public class CharityActivityManager extends javax.swing.JFrame {

    /**
     * Creates new form Equipment
     */
    public CharityActivityManager() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jtxtNameActi = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtxtDateQuit = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtxtDateEnter = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbCharityActi = new javax.swing.JTable();
        jtxtSuport = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jtxtNameOrgani = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jtxtID = new javax.swing.JTextField();
        jbtAdd = new view.JButtonCustom();
        jbtUpdate = new view.JButtonCustom();
        jbttNowActi = new view.JButtonCustom();
        jbtReset = new view.JButtonCustom();
        jtbtDel = new view.JButtonCustom();
        jtbtStopActi = new view.JButtonCustom();
        jLabel7 = new javax.swing.JLabel();
        jtxtFind = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(365, 85, 85, 85));
        setUndecorated(true);
        setSize(new java.awt.Dimension(840, 650));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.RIGHT);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        jLabel3.setText("Tên Hoạt Động");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 110, 110, 40));

        jtxtNameActi.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtxtNameActi.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel2.add(jtxtNameActi, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 110, 260, 40));

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        jLabel4.setText("Thời Gian Kết Thúc");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 170, 140, 40));

        jtxtDateQuit.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtxtDateQuit.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel2.add(jtxtDateQuit, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 170, 260, 40));

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        jLabel5.setText("Thời Gian Bắt Đầu");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 140, 40));

        jtxtDateEnter.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtxtDateEnter.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel2.add(jtxtDateEnter, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 260, 40));

        jtbCharityActi.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jtbCharityActi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã Tổ Chức", "Tên Tổ Chức", "Tên Hoạt Động", "Thời Gian Bắt Đầu", "Thời Gian Kết Thúc", "Tiền/Hiện Vật Ủng Hộ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbCharityActi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jtbCharityActi.setGridColor(new java.awt.Color(0, 204, 204));
        jtbCharityActi.setOpaque(false);
        jtbCharityActi.setRowHeight(40);
        jtbCharityActi.setSelectionBackground(new java.awt.Color(102, 204, 255));
        jtbCharityActi.setShowHorizontalLines(true);
        jtbCharityActi.setShowVerticalLines(true);
        jtbCharityActi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbCharityActiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtbCharityActi);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 1110, 350));

        jtxtSuport.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtxtSuport.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel2.add(jtxtSuport, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 50, 260, 40));

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        jLabel9.setText("Tên Tổ Chức");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 100, 40));

        jLabel10.setBackground(new java.awt.Color(153, 255, 255));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel10.setOpaque(true);
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, 10, 140));

        jtxtNameOrgani.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtxtNameOrgani.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel2.add(jtxtNameOrgani, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 260, 40));

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        jLabel8.setText("Tiền/Hiện vật ủng hộ");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 50, 150, 40));

        jLabel11.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        jLabel11.setText("Mã Tổ Chức");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 100, 40));

        jtxtID.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtxtID.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel2.add(jtxtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 260, 40));

        jbtAdd.setBorder(null);
        jbtAdd.setText("Thêm");
        jbtAdd.setBoderColor(new java.awt.Color(255, 255, 255));
        jbtAdd.setColoOver(new java.awt.Color(255, 102, 51));
        jbtAdd.setColor(new java.awt.Color(51, 255, 153));
        jbtAdd.setColorClick(new java.awt.Color(0, 204, 255));
        jbtAdd.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jbtAdd.setRadius(40);
        jbtAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtAddMouseClicked(evt);
            }
        });
        jPanel2.add(jbtAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 120, 50));

        jbtUpdate.setBorder(null);
        jbtUpdate.setText("Cập Nhật");
        jbtUpdate.setBoderColor(new java.awt.Color(255, 255, 255));
        jbtUpdate.setColoOver(new java.awt.Color(255, 102, 51));
        jbtUpdate.setColor(new java.awt.Color(51, 255, 153));
        jbtUpdate.setColorClick(new java.awt.Color(0, 204, 255));
        jbtUpdate.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jbtUpdate.setRadius(40);
        jPanel2.add(jbtUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 120, 50));

        jbttNowActi.setBorder(null);
        jbttNowActi.setText("Hoạt động hiện tại");
        jbttNowActi.setBoderColor(new java.awt.Color(255, 255, 255));
        jbttNowActi.setColoOver(new java.awt.Color(255, 102, 51));
        jbttNowActi.setColor(new java.awt.Color(51, 255, 153));
        jbttNowActi.setColorClick(new java.awt.Color(0, 204, 255));
        jbttNowActi.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jbttNowActi.setRadius(40);
        jbttNowActi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbttNowActiMouseClicked(evt);
            }
        });
        jPanel2.add(jbttNowActi, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, 150, 50));

        jbtReset.setBorder(null);
        jbtReset.setText("Làm mới");
        jbtReset.setBoderColor(new java.awt.Color(255, 255, 255));
        jbtReset.setColoOver(new java.awt.Color(255, 102, 51));
        jbtReset.setColor(new java.awt.Color(51, 255, 153));
        jbtReset.setColorClick(new java.awt.Color(0, 204, 255));
        jbtReset.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jbtReset.setRadius(40);
        jbtReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtResetMouseClicked(evt);
            }
        });
        jPanel2.add(jbtReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 250, 120, 50));

        jtbtDel.setBorder(null);
        jtbtDel.setText("Xoá");
        jtbtDel.setBoderColor(new java.awt.Color(255, 255, 255));
        jtbtDel.setColoOver(new java.awt.Color(255, 102, 51));
        jtbtDel.setColor(new java.awt.Color(51, 255, 153));
        jtbtDel.setColorClick(new java.awt.Color(0, 204, 255));
        jtbtDel.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jtbtDel.setRadius(40);
        jtbtDel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbtDelMouseClicked(evt);
            }
        });
        jPanel2.add(jtbtDel, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 250, 120, 50));

        jtbtStopActi.setBorder(null);
        jtbtStopActi.setText("Hoạt động đã ngưng");
        jtbtStopActi.setBoderColor(new java.awt.Color(255, 255, 255));
        jtbtStopActi.setColoOver(new java.awt.Color(255, 102, 51));
        jtbtStopActi.setColor(new java.awt.Color(51, 255, 153));
        jtbtStopActi.setColorClick(new java.awt.Color(0, 204, 255));
        jtbtStopActi.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jtbtStopActi.setRadius(40);
        jtbtStopActi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbtStopActiMouseClicked(evt);
            }
        });
        jPanel2.add(jtbtStopActi, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 250, 180, 50));

        jTabbedPane1.addTab("tab1", jPanel2);

        jPanel3.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -50, 1160, 650));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1110, 600));

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        jLabel7.setText("Tìm Theo Tên Tổ Chức");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 170, 40));

        jtxtFind.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtxtFind.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(jtxtFind, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 400, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 660));

        setSize(new java.awt.Dimension(1105, 650));
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCustom1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCustom1MouseClicked

        this.setVisible(false);
    }//GEN-LAST:event_jButtonCustom1MouseClicked

    private void jbtDelelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtDelelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtDelelActionPerformed

    private void jbtDelelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtDelelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtDelelMouseClicked

    private void jtbCharityActiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbCharityActiMouseClicked

    }//GEN-LAST:event_jtbCharityActiMouseClicked

    private void jbtAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtAddMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtAddMouseClicked

    private void jbtUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtUpdateMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtUpdateMouseClicked

    private void jbtUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtUpdateActionPerformed

    private void jbttNowActiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbttNowActiMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbttNowActiMouseClicked

    private void jbtResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtResetMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtResetMouseClicked

    private void jtbtDelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbtDelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jtbtDelMouseClicked

    private void jtbtStopActiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbtStopActiMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jtbtStopActiMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CharityActivityManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CharityActivityManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CharityActivityManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CharityActivityManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CharityActivityManager().setVisible(true);
            }
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private view.JButtonCustom jbtAdd;
    private view.JButtonCustom jbtReset;
    private view.JButtonCustom jbtUpdate;
    private view.JButtonCustom jbttNowActi;
    private javax.swing.JTable jtbCharityActi;
    private view.JButtonCustom jtbtDel;
    private view.JButtonCustom jtbtStopActi;
    private javax.swing.JTextField jtxtDateEnter;
    private javax.swing.JTextField jtxtDateQuit;
    private javax.swing.JTextField jtxtFind;
    private javax.swing.JTextField jtxtID;
    private javax.swing.JTextField jtxtNameActi;
    private javax.swing.JTextField jtxtNameOrgani;
    private javax.swing.JTextField jtxtSuport;
    // End of variables declaration//GEN-END:variables
}
