/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.viewStaffManager;

/**
 *
 * @author ADMIN
 */
public class ExtracurricularActivities extends javax.swing.JFrame {

    /**
     * Creates new form Equipment
     */
    public ExtracurricularActivities() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jlbCountDone = new javax.swing.JLabel();
        jtxtState = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtxtDateQuit = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtxtDateEnter = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbEquipment = new javax.swing.JTable();
        jtxtName = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jlbCountCurrent1 = new javax.swing.JLabel();
        jbtAdd = new view.JButtonCustom();
        jbtAdd2 = new view.JButtonCustom();
        jbtAdd3 = new view.JButtonCustom();
        jbtAdd4 = new view.JButtonCustom();
        jbtAdd5 = new view.JButtonCustom();
        jbtAdd6 = new view.JButtonCustom();
        jLabel7 = new javax.swing.JLabel();
        jtxtFind = new javax.swing.JTextField();
        jbtAdd1 = new view.JButtonCustom();
        jbtAdd7 = new view.JButtonCustom();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(365, 85, 85, 85));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(840, 650));
        setSize(new java.awt.Dimension(840, 650));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.RIGHT);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbCountDone.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        jPanel2.add(jlbCountDone, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 10, 50, 40));

        jtxtState.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtxtState.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel2.add(jtxtState, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 80, 240, 40));

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        jLabel4.setText("Thời Gian Kết Thúc");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 150, 140, 40));

        jtxtDateQuit.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtxtDateQuit.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel2.add(jtxtDateQuit, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 150, 240, 40));

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        jLabel5.setText("Thời Gian Bắt Đầu");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 140, 40));

        jtxtDateEnter.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtxtDateEnter.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel2.add(jtxtDateEnter, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 240, 40));

        jtbEquipment.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jtbEquipment.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã Hoạt Động", "Tên Hoạt Động", "Địa Điểm", "Số cán bộ tham gia", "Số trẻ tham gia", "Thời Gian Bắt Đầu", "Thời Gian Kết Thúc"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbEquipment.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jtbEquipment.setGridColor(new java.awt.Color(0, 204, 204));
        jtbEquipment.setOpaque(false);
        jtbEquipment.setRowHeight(40);
        jtbEquipment.setSelectionBackground(new java.awt.Color(102, 204, 255));
        jtbEquipment.setShowHorizontalLines(true);
        jtbEquipment.setShowVerticalLines(true);
        jtbEquipment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbEquipmentMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtbEquipment);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 1100, 300));

        jtxtName.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtxtName.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel2.add(jtxtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 240, 40));

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        jLabel9.setText("Tên Hoạt Động");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 110, 40));

        jLabel10.setBackground(new java.awt.Color(153, 255, 255));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel10.setOpaque(true);
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 80, 10, 120));

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/sum_24px.png"))); // NOI18N
        jLabel8.setText("Tổng hoạt động đã triển khai:");
        jLabel8.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, 240, 40));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/sum_24px.png"))); // NOI18N
        jLabel12.setText("Tổng hoạt động hiện nay: ");
        jLabel12.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel12.setOpaque(true);
        jLabel12.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 210, 40));

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        jLabel6.setText("Địa Điểm");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 80, 90, 40));

        jlbCountCurrent1.setBackground(new java.awt.Color(255, 255, 255));
        jlbCountCurrent1.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        jlbCountCurrent1.setOpaque(true);
        jPanel2.add(jlbCountCurrent1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, 50, 40));

        jbtAdd.setBorder(null);
        jbtAdd.setText("Hoạt động đã kết thúc");
        jbtAdd.setBoderColor(new java.awt.Color(255, 255, 255));
        jbtAdd.setColoOver(new java.awt.Color(255, 102, 51));
        jbtAdd.setColor(new java.awt.Color(51, 255, 153));
        jbtAdd.setColorClick(new java.awt.Color(0, 204, 255));
        jbtAdd.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jbtAdd.setRadius(40);
        jbtAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtAddMouseClicked(evt);
            }
        });
        jPanel2.add(jbtAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 230, 190, 50));

        jbtAdd2.setBorder(null);
        jbtAdd2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Delete_24px.png"))); // NOI18N
        jbtAdd2.setText("Xoá");
        jbtAdd2.setBoderColor(new java.awt.Color(255, 255, 255));
        jbtAdd2.setColoOver(new java.awt.Color(255, 102, 51));
        jbtAdd2.setColor(new java.awt.Color(51, 255, 153));
        jbtAdd2.setColorClick(new java.awt.Color(0, 204, 255));
        jbtAdd2.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jbtAdd2.setRadius(40);
        jbtAdd2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtAdd2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtAdd2MouseClicked(evt);
            }
        });
        jPanel2.add(jbtAdd2, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 230, 100, 50));

        jbtAdd3.setBorder(null);
        jbtAdd3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/update_24px.png"))); // NOI18N
        jbtAdd3.setText("Cập Nhật");
        jbtAdd3.setBoderColor(new java.awt.Color(255, 255, 255));
        jbtAdd3.setColoOver(new java.awt.Color(255, 102, 51));
        jbtAdd3.setColor(new java.awt.Color(51, 255, 153));
        jbtAdd3.setColorClick(new java.awt.Color(0, 204, 255));
        jbtAdd3.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jbtAdd3.setRadius(40);
        jbtAdd3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtAdd3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtAdd3MouseClicked(evt);
            }
        });
        jPanel2.add(jbtAdd3, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 230, 120, 50));

        jbtAdd4.setBorder(null);
        jbtAdd4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/list_view_24px.png"))); // NOI18N
        jbtAdd4.setText("Hiển Thị");
        jbtAdd4.setBoderColor(new java.awt.Color(255, 255, 255));
        jbtAdd4.setColoOver(new java.awt.Color(255, 102, 51));
        jbtAdd4.setColor(new java.awt.Color(51, 255, 153));
        jbtAdd4.setColorClick(new java.awt.Color(0, 204, 255));
        jbtAdd4.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jbtAdd4.setRadius(40);
        jbtAdd4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtAdd4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtAdd4MouseClicked(evt);
            }
        });
        jPanel2.add(jbtAdd4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 230, 120, 50));

        jbtAdd5.setBorder(null);
        jbtAdd5.setText("Hoạt động hiện tại");
        jbtAdd5.setBoderColor(new java.awt.Color(255, 255, 255));
        jbtAdd5.setColoOver(new java.awt.Color(255, 102, 51));
        jbtAdd5.setColor(new java.awt.Color(51, 255, 153));
        jbtAdd5.setColorClick(new java.awt.Color(0, 204, 255));
        jbtAdd5.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jbtAdd5.setRadius(40);
        jbtAdd5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtAdd5MouseClicked(evt);
            }
        });
        jPanel2.add(jbtAdd5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 170, 50));

        jbtAdd6.setBorder(null);
        jbtAdd6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/add_24px.png"))); // NOI18N
        jbtAdd6.setText("Thêm");
        jbtAdd6.setBoderColor(new java.awt.Color(255, 255, 255));
        jbtAdd6.setColoOver(new java.awt.Color(255, 102, 51));
        jbtAdd6.setColor(new java.awt.Color(51, 255, 153));
        jbtAdd6.setColorClick(new java.awt.Color(0, 204, 255));
        jbtAdd6.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jbtAdd6.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jbtAdd6.setRadius(40);
        jbtAdd6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtAdd6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtAdd6MouseClicked(evt);
            }
        });
        jPanel2.add(jbtAdd6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 100, 50));

        jTabbedPane1.addTab("tab1", jPanel2);

        jPanel3.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1160, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1110, 600));

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        jLabel7.setText("Tìm Theo Tên Hoạt Động");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 170, 40));

        jtxtFind.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtxtFind.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(jtxtFind, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 400, 40));

        jbtAdd1.setBorder(null);
        jbtAdd1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/search_24px.png"))); // NOI18N
        jbtAdd1.setBoderColor(new java.awt.Color(255, 255, 255));
        jbtAdd1.setColoOver(new java.awt.Color(51, 255, 204));
        jbtAdd1.setColorClick(new java.awt.Color(0, 204, 255));
        jbtAdd1.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jbtAdd1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtAdd1MouseClicked(evt);
            }
        });
        jPanel1.add(jbtAdd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 0, 50, 40));

        jbtAdd7.setBorder(null);
        jbtAdd7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/reset_24px.png"))); // NOI18N
        jbtAdd7.setBoderColor(new java.awt.Color(255, 255, 255));
        jbtAdd7.setColoOver(new java.awt.Color(51, 255, 204));
        jbtAdd7.setColorClick(new java.awt.Color(0, 204, 255));
        jbtAdd7.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jbtAdd7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtAdd7MouseClicked(evt);
            }
        });
        jPanel1.add(jbtAdd7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 650));

        setSize(new java.awt.Dimension(1101, 650));
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCustom1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCustom1MouseClicked

        this.setVisible(false);
    }//GEN-LAST:event_jButtonCustom1MouseClicked

    private void jbtDelelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtDelelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtDelelActionPerformed

    private void jbtDelelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtDelelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtDelelMouseClicked

    private void jbtAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtAddActionPerformed

    private void jbtAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtAddMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtAddMouseClicked

    private void jtbEquipmentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbEquipmentMouseClicked

    }//GEN-LAST:event_jtbEquipmentMouseClicked

    private void jbtResestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtResestActionPerformed

    }//GEN-LAST:event_jbtResestActionPerformed

    private void jbtResestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtResestMouseClicked

    }//GEN-LAST:event_jbtResestMouseClicked

    private void jbtUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtUpdateActionPerformed

    private void jbtUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtUpdateMouseClicked

    }//GEN-LAST:event_jbtUpdateMouseClicked

    private void jbtAdd1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtAdd1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtAdd1MouseClicked

    private void jbtAdd2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtAdd2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtAdd2MouseClicked

    private void jbtAdd3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtAdd3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtAdd3MouseClicked

    private void jbtAdd4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtAdd4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtAdd4MouseClicked

    private void jbtAdd5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtAdd5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtAdd5MouseClicked

    private void jbtAdd6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtAdd6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtAdd6MouseClicked

    private void jbtAdd7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtAdd7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtAdd7MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExtracurricularActivities.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExtracurricularActivities.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExtracurricularActivities.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExtracurricularActivities.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExtracurricularActivities().setVisible(true);
            }
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private view.JButtonCustom jbtAdd;
    private view.JButtonCustom jbtAdd1;
    private view.JButtonCustom jbtAdd2;
    private view.JButtonCustom jbtAdd3;
    private view.JButtonCustom jbtAdd4;
    private view.JButtonCustom jbtAdd5;
    private view.JButtonCustom jbtAdd6;
    private view.JButtonCustom jbtAdd7;
    private javax.swing.JLabel jlbCountCurrent1;
    private javax.swing.JLabel jlbCountDone;
    private javax.swing.JTable jtbEquipment;
    private javax.swing.JTextField jtxtDateEnter;
    private javax.swing.JTextField jtxtDateQuit;
    private javax.swing.JTextField jtxtFind;
    private javax.swing.JTextField jtxtName;
    private javax.swing.JTextField jtxtState;
    // End of variables declaration//GEN-END:variables
}
